export const sponsorDefaultValues = {
  sponsorId: "",
  sponsorName: "",
  sponsorFatherName: "",
  sponsorGrandfatherName: "",
  sponsorFamilyName: "",
  sponsorBirthDate: null,
  sponsorGender: "",
  sponsorWorkType: "",
  sponsorCountry: "",
  sponsorCity: "",
  sponsorStreet: "",
  sponsorPhone: "",
  sponsorHomePhone: "",
  sponsorEmail: "",

  paymentMethod: "",

  BankName: "",
  BranchNumber: "",
  bankAccount: "",
  AccountHolderName: "",
  IBAN: "",

  monthlyAmount: "",
  sponsorshipStartDate: null,
  sponsorshipEndDate: null,

  agentId: "",
  agentName: "",
  agentFatherName: "",
  agentGrandfatherName: "",
  agentFamilyName: "",
  agentWorkType: "",
  agentGender: "",
  agentKinship: "",
  agentPhone: "",
  agentCountry: "",
  agentCity: "",
  agentStreet: "",
};
