// ============================================================
// Mock Data for Orphan Center Management System — Admin Panel
// ============================================================

export const orphans = [
  {
    id: 1,
    name: "أحمد محمد",
    age: 8,
    gender: "ذكر",
    dateOfBirth: "2018-03-15",
    enrollmentDate: "2022-01-10",
    sponsorId: 1,
    healthStatus: "جيد",
    educationLevel: "الصف الثالث",
    notes: "طالب متفوق في دراسته",
  },
  {
    id: 2,
    name: "فاطمة علي",
    age: 10,
    gender: "أنثى",
    dateOfBirth: "2016-07-22",
    enrollmentDate: "2021-09-05",
    sponsorId: 2,
    healthStatus: "جيد",
    educationLevel: "الصف الخامس",
    notes: "تحب الرسم والفنون",
  },
  {
    id: 3,
    name: "عمر خالد",
    age: 6,
    gender: "ذكر",
    dateOfBirth: "2020-01-30",
    enrollmentDate: "2023-03-20",
    sponsorId: null,
    healthStatus: "يحتاج متابعة",
    educationLevel: "الصف الأول",
    notes: "يحتاج دعم نفسي",
  },
  {
    id: 4,
    name: "مريم سعيد",
    age: 12,
    gender: "أنثى",
    dateOfBirth: "2014-11-08",
    enrollmentDate: "2020-06-15",
    sponsorId: 3,
    healthStatus: "جيد",
    educationLevel: "الصف السابع",
    notes: "متفوقة في الرياضيات",
  },
  {
    id: 5,
    name: "يوسف حسن",
    age: 9,
    gender: "ذكر",
    dateOfBirth: "2017-05-12",
    enrollmentDate: "2022-08-01",
    sponsorId: null,
    healthStatus: "جيد",
    educationLevel: "الصف الرابع",
    notes: "",
  },
  {
    id: 6,
    name: "ليلى إبراهيم",
    age: 7,
    gender: "أنثى",
    dateOfBirth: "2019-09-25",
    enrollmentDate: "2023-01-12",
    sponsorId: 4,
    healthStatus: "جيد",
    educationLevel: "الصف الثاني",
    notes: "هادئة ومجتهدة",
  },
  {
    id: 7,
    name: "محمد عبدالله",
    age: 11,
    gender: "ذكر",
    dateOfBirth: "2015-02-18",
    enrollmentDate: "2021-04-30",
    sponsorId: null,
    healthStatus: "يحتاج نظارة",
    educationLevel: "الصف السادس",
    notes: "يحب كرة القدم",
  },
  {
    id: 8,
    name: "نور الهدى",
    age: 5,
    gender: "أنثى",
    dateOfBirth: "2021-06-03",
    enrollmentDate: "2024-01-15",
    sponsorId: null,
    healthStatus: "جيد",
    educationLevel: "تمهيدي",
    notes: "أصغر طفلة في المركز",
  },
];

export const donations = [
  {
    id: 1,
    donorName: "عبدالرحمن الشمري",
    amount: 5000,
    currency: "ر.س",
    date: "2024-12-01",
    type: "مالية",
    status: "مستلمة",
    notes: "تبرع شهري",
  },
  {
    id: 2,
    donorName: "هدى القحطاني",
    amount: 2500,
    currency: "ر.س",
    date: "2024-11-20",
    type: "مالية",
    status: "مستلمة",
    notes: "تبرع لمشروع التعليم",
  },
  {
    id: 3,
    donorName: "مؤسسة الخير",
    amount: 15000,
    currency: "ر.س",
    date: "2024-11-15",
    type: "مالية",
    status: "معلقة",
    notes: "بانتظار التحويل البنكي",
  },
  {
    id: 4,
    donorName: "سعد العتيبي",
    amount: 0,
    currency: "ر.س",
    date: "2024-11-10",
    type: "عينية",
    status: "مستلمة",
    notes: "ملابس شتوية — 50 قطعة",
  },
  {
    id: 5,
    donorName: "ليلى الحربي",
    amount: 8000,
    currency: "ر.س",
    date: "2024-10-28",
    type: "مالية",
    status: "مستلمة",
    notes: "تبرع سنوي",
  },
  {
    id: 6,
    donorName: "جمعية البر",
    amount: 20000,
    currency: "ر.س",
    date: "2024-10-15",
    type: "مالية",
    status: "مستلمة",
    notes: "دعم مشروع الترميم",
  },
];



export const sponsors = [
  {
    id: 1,
    name: "خالد العلي",
    phone: "0501234567",
    email: "khaled@example.com",
    orphanId: 1,
    monthlyAmount: 1500,
    startDate: "2022-01-15",
    status: "نشط",
  },
  {
    id: 2,
    name: "سارة حسن",
    phone: "0559876543",
    email: "sara@example.com",
    orphanId: 2,
    monthlyAmount: 1200,
    startDate: "2021-10-01",
    status: "نشط",
  },
  {
    id: 3,
    name: "نورة الأحمد",
    phone: "0541112233",
    email: "noura@example.com",
    orphanId: 4,
    monthlyAmount: 1800,
    startDate: "2020-07-20",
    status: "نشط",
  },
  {
    id: 4,
    name: "فاطمة الزهراء",
    phone: "0533344556",
    email: "fatima@example.com",
    orphanId: 6,
    monthlyAmount: 1000,
    startDate: "2023-02-01",
    status: "نشط",
  },
];

export const helpRequests = [
  {
    id: 1,
    requesterName: "أم أحمد",
    requestType: "مساعدة مالية",
    date: "2024-12-05",
    status: "قيد المراجعة",
    urgency: "عاجل",
    description: "تحتاج مساعدة في مصاريف العلاج",
    phone: "0501234567",
  },
  {
    id: 2,
    requesterName: "أبو محمد",
    requestType: "مساعدة عينية",
    date: "2024-12-03",
    status: "تمت الموافقة",
    urgency: "متوسط",
    description: "يحتاج أثاث منزلي",
    phone: "0559876543",
  },
  {
    id: 3,
    requesterName: "فاطمة علي",
    requestType: "مساعدة تعليمية",
    date: "2024-11-28",
    status: "منتهية",
    urgency: "عادي",
    description: "مساعدة في الرسوم الدراسية",
    phone: "0541112233",
  },
  {
    id: 4,
    requesterName: "خديجة سالم",
    requestType: "مساعدة طبية",
    date: "2024-12-08",
    status: "قيد المراجعة",
    urgency: "عاجل",
    description: "تحتاج عملية جراحية عاجلة",
    phone: "0533344556",
  },
  {
    id: 5,
    requesterName: "عائشة محمود",
    requestType: "مساعدة مالية",
    date: "2024-11-25",
    status: "مرفوضة",
    urgency: "عادي",
    description: "طلب مساعدة في الإيجار",
    phone: "0567788990",
  },
];

// Dashboard summary stats (computed from sponsorId relationship)
export const dashboardStats = {
  totalOrphans: orphans.length,
  sponsoredOrphans: orphans.filter((o) => o.sponsorId != null).length,
  unsponsoredOrphans: orphans.filter((o) => o.sponsorId == null).length,
  totalDonations: donations.reduce((sum, d) => sum + d.amount, 0),

  totalSponsors: sponsors.length,
  pendingRequests: helpRequests.filter((h) => h.status === "قيد المراجعة").length,
};
